### PR TITLE
Carry comments from Rust to C

### PR DESCRIPTION
**Pull request by msprotz**

### CODE REVIEW

**Comment by msprotz** [comment]
To be re-run once fstarlang/karamel#483 gets merged

**Comment by msprotz** [comment]
@Nadrieril should we make kyber a requirement before merging a PR here? Or is it not made a required check to allow asynchronous fixing of the two?

**Comment by msprotz** [comment]
Just realized this got merged without kyber coming back green

**Comment by Nadrieril** [comment]
It's not a requirement because libcrux doesn't have processes in place to make it reliably be green.

**Pull request merged**
